### PR TITLE
Git chapter revisions

### PR DESCRIPTION
**Pull request by mhasoba**
Made changes to strcuture and added a list of common mistakes while brancing in teamwork.

### CODE REVIEW

**Comment by mhasoba** [comment]
@smith558 , can you please review changes to this chapter?

**Comment by fwimp** [comment]
Accidentally reviewed this one too, so here are my notes on the chapter:

## General
- Cells with `{admonition}` code blocks do not _seem_ to render at least for me.
## Why Git
- The bullet about "Data Integrity" is indefensible. Git does not checksum, lint, parse, or error-correct files on its own. You can use CI, hooks, or pre-push checks to do this, but that is a different (and advanced) thing which should be explained if we want to make this point.
## Installing git
- New git configuration explanation is excellent, really useful addition.
## Your first repository
- "Check your git configuration:" seems to just show nothing afterwards.
- Spelling error: "Check agin git config --list to see if anything has changed." -> "Check git config --list again to see if anything has changed."
- Tip about git flag combination uses the `-a` flag even though that hasn't yet been introduced (and possibly we should not introduce students to so early as it's generally a bad thing to do without experience).
- Weird blank cell at the end (at least on my machine).
## Commits
- "A unique hash (SHA-1 checksum) in Git" should say "The unique hash (SHA-1 checksum) in Git"
## Your remote repository
- Do we need to really tell them how to rename their remote? Frankly I rarely have to do that, and more often than not it's more worth keeping origin as the default unless you have a good reason for changing it, just as it makes debugging easier.
## Dealing with large files
- One of the elements (3) in the Pre-Commit Git Hook section does not render properly.
## Branching
- LaTeX logo is accidentally double-escaped leading to it not properly rendering.
- Commands below this demonstrating branches are in individual boxes with nothing separating them. They should either show the output, or be formatted into one code cell (or a multiline code fence within a markdown cell using triple backticks)
## Common mistakes
- (1.) Working directly on the main branch is bad when working in a team obviously, but we should really set them up with something like git-flow to give them a structure for working collaboratively rather than just telling them to use branches and making them figure it out for themselves. I see that we sort of talk about it in point 15, but maybe this should be moved up to be directly below point 1.
- (2.) Similarly, not pulling latest changes is not a problem if you are on a branch which no-one else is working on, or one which is not tracked by a branch on the remote. If we really want to solve the problem described here, we also need to talk about rebasing etc. so they have a method for harmonising new commits on main with their branch prior to merging.
- (10.) We shouldn't mention CI if we haven't introduced the concept before. That's just going to be very confusing, though it is absolutely a valid point.

**Comment by mhasoba** [comment]
@fwimp , thank you!

I am making changes accordingly. 

BTW, Git does generate a checksum (that is one of the the core objectives of git) for each of the changesets (that covers all objects in  repo). The hash value represents this: https://git-scm.com/book/en/v2/Git-Internals-Git-Objects 

Granted it does not do any linting etc, but that does not come under data integrity

**Comment by mhasoba** [comment]
OK, have made updates based on @fwimp's review

**Comment by fwimp** [comment]
Re: integrity. I'd still say that git does not check to see whether the file is a valid file in any meaningful way. It checks to make sure that the git object is as it says it is, but does nothing about ensuring that the file is a valid file for its purpose. This is clearer in the rework thought so that looks good.

Feedback on the new version:
## Your first repository
- `ll` is equivalent to `ls -al`, not `ls -ltr` (which would be nearly equivalent to `ll -tr`, useful but not quite the same)
- Still got that odd blank cell at the end, just above Fig. 9

Other than that, looks great! Not sure if @smith558 has anything to add?

**Comment by smith558** [comment]
@fwimp  I am a bit swamped today but following this conversation closely. 🙂 To be fair, I feel like you are more than well standing in for the reviewer, so I may just add something later.

**Comment by mhasoba** [comment]
@fwimp , I have addressed everything except the mystery code box - not sure what's going on, but I reckon its some obscure Jupyter book quirk (can be revisited later). 

Please approve for merge.

**Review by fwimp — APPROVED** [review]
Final changes made appropriately and no obvious regressions.

**Pull request merged**
